kind: Service
apiVersion: v1
metadata:
  name: frontend
spec:
  type: NodePort

  selector:
    app: portfolio-frontend

  ports:
    # nodePort - a static port assigned on each the node
    # port - port exposed internally in the cluster
    # targetPort - the container port to send requests to
    - port: 5000
      targetPort: 5000
